pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Xposed / LSPosed API (compileOnly)
        maven { url 'https://api.xposed.info/' }
    }
}

rootProject.name = 'OplusOtaTracer'
include ':app'
